apiVersion: v1
kind: Service 
metadata:
  name: datagrid2-nodeport
spec:
  type: NodePort 
  clusterIP: 10.1.6.170
  ports:
  - port: 80
    targetPort: 7077
    nodePort: 30123
  selector:
    app: datagrid2-ng
